---
kind: pipeline
name: argosbuild
type: docker

services:
  - name: registry
    image: registry
    ports:
      - 443:5000

steps:
# build docker images
  - name: build argos service image
    image: plugins/docker
    settings:
      repo: registry/rabobanknl/argos-jenkins
      tags: latest
      context: docker
      dockerfile: docker/JenkinsDockerfile
      registry: registry
      insecure: true
    depends_on:
     - registry
 
  - name: argos-jenkins
    image: registry/rabobanknl/argos-jenkins:latest
    commands:
      - echo hallo
    insecure: true
    depends_on:
     - build argos service image
     - registry
#   - name: regression test
#     image: rabobanknl/argos-build:latest
#     commands:
#       - ping argos-jenkins
#       - sleep 300
#     depends_on:
#      - build argos service image
     
#image_pull_secrets:
#   - dockerconfig

trigger:
  event:
    - push
    - pull_request
