---
kind: pipeline
name: argosbuild
type: docker

services:
  - name: registry
    image: registry

steps:
# build docker images
  - name: build argos service image
    image: plugins/docker
    settings:
      repo: registry:5000/rabobanknl/argos-jenkins
      tags: latest
      context: docker
      dockerfile: docker/JenkinsDockerfile
      registry: registry:5000
      insecure: true
    depends_on:
     - registry
     
  - name: ping registry
    image: busybox
    commands:
      - ping registry
    depends_on:
     - registry
  - name: regression test
    image: rabobanknl/argos-build:latest
    commands:
      - ping argos-jenkins
      - sleep 300
    depends_on:
     - build argos service image
 
  - name: argos-jenkins
    image: registry:5000/rabobanknl/argos-jenkins:latest
    pull: always
    insecure: true
    commands:
      - echo hallo
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    depends_on:
     - build argos service image
     - registry
  - name: regression test
    image: rabobanknl/argos-build:latest
    commands:
      - ping argos-jenkins
      - sleep 300
    depends_on:
     - build argos service image
     
image_pull_secrets:
   - dockerconfig

trigger:
  event:
    - push
    - pull_request
